name: AWS DEPLOY TO STAGING

#turn off deploy to AWS
on:
  push:
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    #For google auth

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "3.142.71.232"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/resume-frontend"
